import type { Metadata } from 'next'
import "./globals.css";
import Contents from './components/contents'

export const metadata: Metadata = {
  title: 'jsh',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className="bg-eggshelly flex w-full h-screen text-inky"
      >
      <Contents/>
        {children}
      </body>
    </html>
  )
}
